### PR TITLE
feat: update frictionless to v5.13.1

### PR DESCRIPTION
**Pull request by ChasNelson1990**
Tested this locally on a vanilla ckan and all tests pass fine. Seems like a simple update! Wahoo :tada:

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Comment by ThrawnCA** [comment]
What version(s) of CKAN did you test? 2.9, 2.10, or latest master?

**Comment by ChasNelson1990** [comment]
> What version(s) of CKAN did you test? 2.9, 2.10, or latest master?

I tested 2.9 and 2.10

**Comment by ChasNelson1990** [comment]
...sorry pressed the "close with comment" button by accident.

**Comment by duttonw** [comment]
now at frictionless==5.18.0

**Pull request closed without merging**
